version: '3.9'

services:
  web:
    build:
      context: .  # Use the current directory for the web app
      dockerfile: Dockerfile  # Dockerfile for the web app
    ports:
      - "5000:5001"  # Map port 5000 of the container to port 5000 of the host
    volumes:
      - .:/app  # Mount the current directory to `/app` in the container
    depends_on:
      - ml  # Ensure ML service starts before the web app
    environment:
      - MONGO_URI=mongodb://mongodb:27017/  # MongoDB connection for the web app
      - ML_CLIENT_URL=http://ml:5001/process  # ML service connection
      - SECRET_KEY=your_secret_key  # Flask app secret key

  ml:
    build:
      context: ./machine-learning-client  # Use the machine-learning-client directory
      dockerfile: Dockerfile  # Dockerfile for the ML service
    ports:
      - "5001:5001"  # Map port 5001 of the container to port 5001 of the host
    volumes:
      - ./machine-learning-client:/app  # Mount the machine-learning-client folder to `/app`
    depends_on:
      - mongodb  # Ensure MongoDB starts before the ML service
    environment:
      - MONGO_URI=mongodb://mongodb:27017/  # MongoDB connection for the ML app

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"  # Map port 27017 of the container to port 27017 of the host
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data

volumes:
  mongo_data:  # Named volume for MongoDB data persistence
