version: '3.9'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 5000 in the container
    volumes:
      - .:/app       # Sync local code with the container
    depends_on:
      - mongodb      # Ensure MongoDB starts before the web app

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"  # Map port 27017 on the host to port 27017 in the container
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data

volumes:
  mongo_data:               # Named volume for MongoDB data persistence
