version: '3.9'
services:

  ml-client:
    build:
      context: .
    container_name: ml-client-container
    ports:
      - "5001:5001"
    networks:
      - app-network
    depends_on:
      - mongodb

  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 5000 in the container
    volumes:
      - .:/app       # Sync local code with the container
    depends_on:
      - mongodb      # Ensure MongoDB starts before the web app
      - ml-client      

  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"  # Map port 27017 on the host to port 27017 in the container
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data
    networks:
      - app-network  

volumes:
  mongo_data:               # Named volume for MongoDB data persistence
